config/routes.rb
Rails.application.routes.draw do
  resources :tags, only: :show
  resources :sites
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sites#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/site.rb
class Site < ApplicationRecord
  has_one :tag, dependent: :destroy
  after_save :update_or_create_tag

  private

  def update_or_create_tag
      tag_params = Tag.tag_params(url)
      tag_params['links'] = ['links'].uniq.collect do |href|
        URI.join(url, href).to_s
      end
      if tag.present?
        tag.update(tag_params)
      else
        build_tag(tag_params)
      end
      tag.save!
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :site

  def self.tag_params(url)
    Wombat.crawl do
      base_url url

      h1({xpath: "//h1"}, :list)
      h2({xpath: "//h2"}, :list)
      h3({xpath: "//h3"}, :list)

      links({ xpath: "//a/@href" }, :list)

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]

  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url, notice: 'Site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:url)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
  def html_safe_content(content)
    content_array = JSON.parse(content).reject { |c| c.empty? }
    content_array.present? ? content_array.join('</br>').html_safe : []
  end
end

app/views/layouts/_nav_header.html.erb
<nav>
  <div class="nav-wrapper">
    <div class="container">
        <a href="#" class="brand-logo">LimApp</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="/">Sites</a></li>
        </ul>
    </div>
  </div>
</nav>
        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LimApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/nav_header' %>
    </header>
    <div class="container">
        <%= yield %>
    </div>
  </body>
</html>

app/views/sites/_form.html.erb
<%= form_with(model: site, local: true) do |form| %>
  <% if site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.url_field :url, id: :site_url, required: true %>
  </div>

  <div class="actions">
    <button class="btn waves-effect waves-light" type="submit" name="action">Submit
      <i class="material-icons right">send</i>
    </button>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing Site</h1>

<%= render 'form', site: @site %>

<br/>
<a  href="<%= site_path(@site) %>" class="waves-effect waves-light btn">Show</a>
<a  href="<%= sites_path %>" class="waves-effect waves-light btn">Back</a>

app/views/sites/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Sites</h3>
<a href="<%= new_site_path %>" class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">add</i></a>
<table>
  <thead>
    <tr>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sites.each do |site| %>
      <tr>
        <td><%= site.url %></td>
        <td><%= link_to 'Show Tags', tag_path(site.tag), class: 'waves-effect waves-light btn' %></td>
        <td><%= link_to 'Edit', edit_site_path(site), class: "waves-effect waves-light btn" %></td>
        <td><%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-light btn" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<a href="<%= new_site_path %>" class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">add</i></a>

app/views/sites/new.html.erb
<h3>New Site</h3>

<%= render 'form', site: @site %>

<%= link_to sites_path, :class => 'btn waves-effect waves-light right'  do %>
    Back
<% end %>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @site.url %>
</p>


<a  href="<%= edit_site_path(@site) %>" class="waves-effect waves-light btn"><i class="material-icons left">mode_edit</i>Edit</a>
<a  href="<%= sites_path %>" class="waves-effect waves-light btn">Back</a>

app/views/tags/show.html.erb
<h3>Tags</h3>
<ul class="collection">
  <li class="collection-item">
    <strong><span class="title">H1:</span></strong>
    <p>
      <%= html_safe_content(@tag.h1) %>
    </p>
  </li>
  <li class="collection-item">
    <strong><span class="title">H2:</span></strong>
    <p>
      <%= html_safe_content(@tag.h2) %>
    </p>
  </li>
  <li class="collection-item">
    <strong><span class="title">H3:</span></strong>
    <p>
      <%= html_safe_content(@tag.h3) %>
    </p>
  </li>
  <li class="collection-item">
    <strong><span class="title">Links:</span></strong>
    <p>
      <%= html_safe_content(@tag.links) %>
    </p>
  </li>
</ul>

<a  href="<%= sites_path %>" class="waves-effect waves-light btn">Back</a>